// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	null "gopkg.in/guregu/null.v4"
)

type Announce struct {
	ID        uuid.UUID        `json:"id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	CreatedAt null.Time        `json:"created_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type Bookmark struct {
	ID      uuid.UUID `json:"id"`
	UserID  string    `json:"user_id"`
	HologID uuid.UUID `json:"holog_id"`
}

type Holog struct {
	ID          uuid.UUID   `json:"id"`
	PlaceID     string      `json:"place_id"`
	CreatorID   string      `json:"creator_id"`
	ScheduleID  pgtype.UUID `json:"schedule_id"`
	Type        string      `json:"type"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	ImageUrl    *string     `json:"image_url"`
	ExternalUrl *string     `json:"external_url"`
	CreatedAt   null.Time   `json:"created_at"`
	DeletedAt   null.Time   `json:"deleted_at"`
}

type Schedule struct {
	ID        uuid.UUID        `json:"id"`
	UserID    string           `json:"user_id"`
	StartDate null.Time        `json:"start_date"`
	EndDate   null.Time        `json:"end_date"`
	CreatedAt null.Time        `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type ScheduleDetail struct {
	ID         uuid.UUID        `json:"id"`
	ScheduleID uuid.UUID        `json:"schedule_id"`
	PlaceID    string           `json:"place_id"`
	CreatedAt  null.Time        `json:"created_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type User struct {
	ID              string    `json:"id"`
	Password        string    `json:"password"`
	Username        string    `json:"username"`
	ProfileImageUrl *string   `json:"profile_image_url"`
	CreatedAt       null.Time `json:"created_at"`
	DeletedAt       null.Time `json:"deleted_at"`
}
