// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Holog struct {
	ID           pgtype.UUID
	PlaceID      int32
	CreatorID    int32
	Type         string
	Title        string
	Content      string
	ThumbnailUrl pgtype.Text
	ExternalUrl  pgtype.Text
	CreatedAt    pgtype.Date
	DeletedAt    pgtype.Timestamp
}

type User struct {
	Email           string
	Password        string
	Username        string
	ProfileImageUrl pgtype.Text
	CreatedAt       pgtype.Date
	DeletedAt       pgtype.Timestamp
}
