basePath: /
definitions:
  api.LoginRequest:
    properties:
      id:
        type: string
      password:
        type: string
    type: object
  api.MyInfoRequest:
    properties:
      id:
        type: string
    type: object
  api.SignUpRequest:
    properties:
      id:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  db.CreateUserRow:
    properties:
      id:
        type: string
      username:
        type: string
    type: object
  db.GetUserByEmailAndPasswordRow:
    properties:
      created_at:
        type: string
      id:
        type: string
      profile_image_url:
        type: string
      username:
        type: string
    type: object
  db.GetUserByIDRow:
    properties:
      created_at:
        type: string
      id:
        type: string
      profile_image_url:
        type: string
      username:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: zhengsfsf@gmail.com
    name: API Support
  description: This is a Hoolo swagger docs for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Hoolo API
  version: "0.1"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login with email and password
      parameters:
      - description: Login Request
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/api.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.GetUserByEmailAndPasswordRow'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: 로그인
      tags:
      - users
  /place/list:
    get:
      consumes:
      - application/json
      description: Get place list randomly
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: 장소 리스트 가져오기(랜덤)
      tags:
      - openapi
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user with email, username and password
      parameters:
      - description: SignUp Request
        in: body
        name: SignUpRequest
        required: true
        schema:
          $ref: '#/definitions/api.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.CreateUserRow'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: 회원가입
      tags:
      - users
  /user/myinfo:
    post:
      consumes:
      - application/json
      description: Get user information by ID
      parameters:
      - description: MyInfo Request
        in: body
        name: MyInfoRequest
        required: true
        schema:
          $ref: '#/definitions/api.MyInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.GetUserByIDRow'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: 내정보 가져오기 (By ID)
      tags:
      - users
swagger: "2.0"
